### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by volkankaban**

### CODE REVIEW

**Comment by teyim** [comment]
Hey @volkankaban , thanks for the PR.. it seems your trying to fix the broken image problem in the Readme.however, this does not fix the problem of the image not displaying in the ReadMe..it seems the image gets corrupted or something .because the image itself does not diaplay..

**Comment by volkankaban** [comment]
Oh I see render error! Did you check your gitignore file?

**Comment by teyim** [comment]
yes..now if the look at this commit [https://github.com/teyim/Walle/commit/713907cd2da3abf19b5161d8c3a7b3b3cb0b62e5](url) you will notice the image actually displays..

**Comment by volkankaban** [comment]
Getting an 404 error

image

**Comment by volkankaban** [comment]
Do you have Twitter or can you DM me somewhere?

**Comment by teyim** [comment]
yeah , i have twitter.., sent you a dm

**Pull request closed without merging**
